# Generated by Django 5.2 on 2025-04-28 08:01

import account.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("--Select--", "--انتخاب کنید--"),
                            ("Person", "حقیقی"),
                            ("Legal", "حقوقی"),
                        ],
                        default="--Select--",
                        max_length=10,
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=100, null=True)),
                ("identifier", models.CharField(max_length=10, unique=True)),
                ("phone", models.CharField(max_length=11, unique=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(
                        default=functools.partial(
                            account.models.default_file,
                            *(),
                            **{"default_dir": "user/default/", "filename": "user3.png"}
                        ),
                        upload_to=functools.partial(
                            account.models.upload_file,
                            *(),
                            **{"upload_dir": "user/upload/"}
                        ),
                    ),
                ),
                ("otp", models.PositiveIntegerField(blank=True, null=True)),
                ("otp_time", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "ordering": ["-created"],
                "indexes": [
                    models.Index(
                        fields=["-created"], name="account_myu_created_f66927_idx"
                    )
                ],
            },
        ),
    ]
